### ISSUE TITLE
Naming refactor

### ISSUE THREAD

**Issue by emaildano** [j2made/gemini#4]
I can't rename `require('scoutUberController');` in [app.js](https://github.com/j2made/gemini/blob/refactor/app/app/app/app.js#L67)

This is to move some progress done with Scout to Gemini so it can be starter boilerplate.

**Comment by baerkins** [comment]
I'd like to keep Gemini as just a blank slate, completely open, js framework agnostic.

I do have a `gemini-ng` project on my machine in the office, which is Gemini written with Angular in mind. Similarly, there may eventually be a `gemini-react` repo as well.

**Comment by emaildano** [comment]
Having the app folder there but blank it's a bit confusing. If we're going that route we should at least add a hello world example with React and/or Angular.

**Comment by baerkins** [comment]
We could put the README on the Index page. https://github.com/j2made/gemini/blob/master/app/index.html

My whole thought process with Gemini was to provide a bare bones way of developing a decoupled system within the same repo. There's a lot of js frameworks, and they all have their perks. There are plenty of Github projects for Angular/React/Underscore/Ember boilerplates, which someone could bring in on their own after they have picked the system. The WP end is a bit more reformatted no matter what library you use, so Gemini takes care of that.

**Comment by emaildano** [comment]
We should put Info in the README but if that's all we're going to do this repo doesn't do much to help someone get started.

Any framework can go into /app but we should provide at minimum an example of one of them.

The example could just display info from a fresh WP install.

**Comment by baerkins** [comment]
Right. I understand the want to do this, but there's a lot that goes in to using one of those libraries. Each one has a preferred setup, different package.json, different gulpfile (or not even a gulpfile as react prefers webpack) which is why there would be a gemini-ng, gemini-react, etc. At the base of each of those, however, is this repo.

An example would also involve forcibly creating content in WP, otherwise it's a whole lot of work to display the 'Hello World' blog post or Sample page title, which is the only content you can count on in a fresh install.

It doesn't make this repo worthless to not have an example. It takes care of the composer build, installs all of the WP-API plugins, sets the CMS up to be as blind as possible, and establishes a structure similar to Apollo for functions.

**Comment by baerkins** [comment]
It's also a boilerplate for decoupling Wordpress, getting an app layer separate from the cms. The Readme is fairly clear on that intent.
